apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: test
      app.kubernetes.io/component: test
      app.kubernetes.io/instance: test
    name: test
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: narawitrt/amq-workshop
      from:
        kind: DockerImage
        name: narawitrt/amq-workshop
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: test
      app.kubernetes.io/component: test
      app.kubernetes.io/instance: test
    name: test
  spec:
    replicas: 1
    selector:
      deploymentconfig: test
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deploymentconfig: test
      spec:
        containers:
        - image: narawitrt/amq-workshop
          name: test
          ports:
          - containerPort: 3000
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - test
        from:
          kind: ImageStreamTag
          name: test:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: test
      app.kubernetes.io/component: test
      app.kubernetes.io/instance: test
    name: test
  spec:
    ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      deploymentconfig: test
  status:
    loadBalancer: {}
kind: List
metadata: {}
